### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'task'

### ISSUE THREAD

**Issue by plutokevin** [Victorwz/zs-nmt-dae#2]
I can train the model according to your code, but the result is not good enough, so I want to load your checkpoint, But when I load the _checkpoint_best.pt, code, dict.src.txt_ from [Google Drive](https://drive.google.com/file/d/1HtJ01SRm69rtN6JyZkspilamfO3YjIeD/view?usp=sharing), I have encountered a problem：
**`AttributeError: 'NoneType' object has no attribute 'task'`**
How should I solve this problem?

**Comment by Victorwz** [comment]
Thank you for your interest to our work. Would you please provide the implementation details and setting to let me check the reason of not so good performance?
Secondly, the AttributeError is caused by the Fairseq version mismatch. I have updated the link of our checkpoint in the README file for your reproduction. The checkpoint is now compatible with Fairseq version 0.10.1. Apology for this bug. Looking forward to the future communication.

**Comment by plutokevin** [comment]
> Thank you for your interest to our work. Would you please provide the implementation details and setting to let me check the reason of not so good performance? Secondly, the AttributeError is caused by the Fairseq version mismatch. I have updated the link of our checkpoint in the README file for your reproduction. The checkpoint is now compatible with Fairseq version 0.10.1. Apology for this bug. Looking forward to the future communication.

Thank you for your reply^^, the checkpoint is available now. I retrained my model on four V100, then the results are similar to those shown in the paper, so I think I may not have trained the model sufficiently before. Thanks again for your help!
